apiVersion: apps/v1
kind: Deployment
metadata:
  name: detailmc-deployment 
  labels:
    app: detailmc 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detailmc
  template:
    metadata:
      labels:
        app: detailmc
    spec:
      containers:
      - name: detailmc
        image: pensioncr.azurecr.io/detailmcimage:latest
        resources:
        env:
           - name: ConnectionString
             value: Server = "tcp:authpension.database.windows.net,1433;Initial Catalog=MSTWOPensionDb;Persist Security Info=False;User ID=pension;Password=Subhadip@1202;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: webapisvcsecret  
---


apiVersion: v1
kind: Service
metadata:
  name: detailmcsvc
spec:
  type: LoadBalancer
  selector:
    app: detailmc
  ports:
  - port: 80
