apiVersion: apps/v1
kind: Deployment
metadata:
  name: authmc-deployment 
  labels:
    app: authmc 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authmc
  template:
    metadata:
      labels:
        app: authmc
    spec:
      containers:
      - name: authmc
        image: pensioncr.azurecr.io/authmcimage:latest
        resources:
        env:
           - name: ConnectionString
             value: Server = "tcp:authpension.database.windows.net,1433; Initial Catalog = MSONEPensionDb; Persist Security Info = False; User ID = pension; Password = Subhadip@1202; MultipleActiveResultSets = False; Encrypt = True; TrustServerCertificate = False; Connection Timeout = 30;"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: webapisvcsecret  
---


apiVersion: v1
kind: Service
metadata:
  name: authmcsvc
spec:
  type: LoadBalancer
  selector:
    app: authmc
  ports:
  - port: 80
